# Generated by Django 2.2.6 on 2019-11-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article')),
            ],
        ),
    ]
