# Generated by Django 2.2.6 on 2019-11-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
    ]
