# Generated by Django 2.2.6 on 2019-11-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_read_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
